// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/10/2024, 19:34:04
const configMerger = require("/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/plugins/**/*.{js,ts,mjs}","/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/composables/**/*.{js,ts,mjs}","/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/utils/**/*.{js,ts,mjs}","/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "/Users/dinaab/Desktop/school/atelier-webdesign/porfolio/portfolio/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
